GET http://localhost:3000/api/v1/movies?sortBy=id&page=1&limit=3&order=asc
ontent-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjo0LCJyb2xlIjoidXNlciJ9LCJpYXQiOjE2Mzc4NzU4OTcsImV4cCI6MTYzNzg3OTQ5NywiaXNzIjoiTW92aWUgU2VydmljZSJ9.pO8cUROHgpMQqhQC6XWSrKyMnH6yL5C31Um0x_ovyvE


###

POST http://localhost:3000/api/v1/movies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjo0LCJyb2xlIjoidXNlciJ9LCJpYXQiOjE2Mzc4NzU4OTcsImV4cCI6MTYzNzg3OTQ5NywiaXNzIjoiTW92aWUgU2VydmljZSJ9.pO8cUROHgpMQqhQC6XWSrKyMnH6yL5C31Um0x_ovyvE

{"name": "terminator", "comment": "Some text", "personalScore": 9.9}

###

GET http://localhost:3000/api/v1/movies/4

###

PATCH  http://localhost:3000/api/v1/movies/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoyLCJyb2xlIjoidXNlciJ9LCJpYXQiOjE2Mzc2MTkyMjIsImV4cCI6MTYzNzYyMjgyMiwiaXNzIjoiTW92aWUgU2VydmljZSJ9.NyvC-_CNDIVVOy8uubBLvBfEzk38erdIQ64BDhPS-n0

{"comment": "My favourite movie", "personalScore": 3.7}

###

DELETE  http://localhost:3000/api/v1/movies/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjo0LCJyb2xlIjoidXNlciJ9LCJpYXQiOjE2Mzc4NzU4OTcsImV4cCI6MTYzNzg3OTQ5NywiaXNzIjoiTW92aWUgU2VydmljZSJ9.pO8cUROHgpMQqhQC6XWSrKyMnH6yL5C31Um0x_ovyvE
