GET http://localhost:3000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoxLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjM3ODY4MDI2LCJleHAiOjE2Mzc4NzE2MjYsImlzcyI6Ik1vdmllIFNlcnZpY2UifQ.r0DCg5qc7pMS81ynwGWffFNRSuwHNqbI9qjQxPS2Cdo
###

GET http://localhost:3000/api/v1/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjoxLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjM3ODcyNDUzLCJleHAiOjE2Mzc4NzYwNTMsImlzcyI6Ik1vdmllIFNlcnZpY2UifQ.JUCmiV6L1CHBgv1FSzjLBFUuZ0QRDN4sOHzN19F5JVc

###

POST http://localhost:3000/api/v1/users/favourite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImlkIjo1LCJyb2xlIjoidXNlciJ9LCJpYXQiOjE2Mzc4NzYwNDUsImV4cCI6MTYzNzg3OTY0NSwiaXNzIjoiTW92aWUgU2VydmljZSJ9.OCYCqXaEA2o9fPrT8RS6qzDx9CGoqOvn0ejiQ0H4vnw

{ "movie_id": "1" }
